<?php
namespace App\Normalizer;


use App\Model\DeepModel;
use App\Model\DeepUserModel;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;

class DeepNormalizer extends ObjectNormalizer
{
    public function setAttributeValue(object $object, string $attribute, $value, string $format = null, array $context = [])
    {
//        dump($object, $attribute, $value);
//        dump($attribute, $value);
//        dump($attribute);
//        if ($attribute !== 'data') {
//            return;
//        }

        if (is_array($value)) {
            $this->denormalize($value, DeepUserModel::class, 'json');
            parent::setAttributeValue($object, $attribute, $value, $format, $context); // TODO: Change the autogenerated stub
        }
    }

    public function supportsDenormalization($data, string $type, string $format = null)
    {
        return DeepUserModel::class === $type;
    }
}